version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: docker/backend.Dockerfile
            target: release
        image: labyrinth:latest
        container_name: labyrinth
        expose:
        - 9112
    nginx:
        build: 
            context: ./web-client
            target: release
        image: labyrinth-nginx:latest
        container_name: labyrinth-nginx
        ports:
        - "80:80"
