name: labyrinth

on: push

jobs:
    web-client:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web-client
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
            with:
                install: true
          - name: Lint
            run: |
              docker build --target lint .
          - name: Run tests
            run: |
              docker build --target test .

    algolibs:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
            with:
                install: true
          - name: Run tests
            run: |
              docker build --target algolibs-test --file docker/backend.Dockerfile .
  
    backend:
        runs-on: ubuntu-latest
        needs: [algolibs]
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
            with:
                install: true
          - name: Lint
            run: |
              docker build --target lint --file docker/backend.Dockerfile .
          - name: Run tests
            run: |
              docker build --target test --file docker/backend.Dockerfile .
    release:
        runs-on: ubuntu-latest
        needs: [web-client, algolibs, backend]
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
            with:
                install: true
          - name: Log in to Docker Hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Build and push web-client image
            uses: docker/build-push-action@v2
            with:
                context: ./web-client
                file: ./web-client/Dockerfile
                push: true
                tags: julianarz/labyrinth-web-client:latest
          - name: Build and push backend image
            uses: docker/build-push-action@v2
            with:
                context: ./
                file: ./docker/backend.Dockerfile
                push: true
                tags: julianarz/labyrinth-backend:latest
