name: release

on: 
    workflow_dispatch:
    push:
        tags:
            '[0-9]+.[0-9]+.[0-9]+'

jobs:
    web-client:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Log in to Docker Hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v3
            with:
                images: julianarz/labyrinth-web-client
                tags: |
                  type=ref,priority=600,event=branch
                  type=match,priority=600,pattern=\d.\d.\d
                  type=raw,priority=200,value=latest
          - name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
                context: ./web-client
                file: ./web-client/Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

    backend:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v2
          - name: Log in to Docker Hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v3
            with:
                images: julianarz/labyrinth-backend
                tags: |
                  type=ref,priority=600,event=branch
                  type=match,priority=600,pattern=\d.\d.\d
                  type=raw,priority=200,value=latest
          - name: Build and push Docker image
            uses: docker/build-push-action@v2
            with:
                context: ./
                file: ./docker/backend.Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}